In [19]:
import re
import csv
import json
from pprint import pprint
import numpy as np

In [9]:
# 2.1
nparr = np.array([[1,np.nan,4,np.nan], [1,np.nan,4,5], [1,np.nan,np.nan,5], [1,np.nan,4,5], [np.nan,3,4,5]]) 
print(nparr)

x = np.isnan(nparr)
print(np.isnan(nparr))

print(np.count_nonzero(x))

result = [np.count_nonzero(row) for row in np.isnan(nparr)]
print(result)


[[ 1. nan  4. nan]
 [ 1. nan  4.  5.]
 [ 1. nan nan  5.]
 [ 1. nan  4.  5.]
 [nan  3.  4.  5.]]
[[False  True False  True]
 [False  True False False]
 [False  True  True False]
 [False  True False False]
 [ True False False False]]
7
[2, 1, 2, 1, 1]


In [13]:
nparr = np.array([[1,np.nan,4,np.nan], [1,np.nan,4,5], [1,np.nan,np.nan,5], [1,np.nan,4,5], [np.nan,3,4,5]]) 
x = np.isnan(nparr)
result = np.count_nonzero(x, axis=1)
print(result)

[2 1 2 1 1]


In [36]:

# 2.2
arr = np.arange(1,100).reshape(3, 33)
print(arr)

result = np.where(arr % 2 != 0, arr ** 2, arr)


[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
  58 59 60 61 62 63 64 65 66]
 [67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90
  91 92 93 94 95 96 97 98 99]]


In [62]:
# 2.3
arr = np.random.randint(1,100, (5,6))
print(arr)

[[ 4 81 15 92 32 54]
 [ 8 95 72 40 74 72]
 [61 62 19 82 85 43]
 [74 40 60 54 66 38]
 [ 7 88 50 31 40 89]]


In [63]:
r1 = np.argsort(arr)
print(r1)
print(np.sort(arr))

[[0 2 4 5 1 3]
 [0 3 2 5 4 1]
 [2 5 0 1 3 4]
 [5 1 3 2 4 0]
 [0 3 4 2 1 5]]
[[ 4 15 32 54 81 92]
 [ 8 40 72 72 74 95]
 [19 43 61 62 82 85]
 [38 40 54 60 66 74]
 [ 7 31 40 50 88 89]]


In [64]:
numrow, numcol = arr.shape
largest = np.argsort(arr)[numrow-1][-1]
secondlargest = np.argsort(arr)[numrow-1][-2]

smallest = np.argsort(arr)[0][0]
secondsmallest = np.argsort(arr)[0][1]

print(smallest, secondsmallest, largest, secondlargest)

0 2 5 1


In [68]:
arr2 = arr.copy()
temp = arr[0][smallest]
arr2[0][smallest] = arr2[numrow-1][largest]
arr2[numrow-1][largest] = temp

temp = arr[0][secondsmallest]
arr2[0][secondsmallest] = arr2[numrow-1][secondlargest]
arr2[numrow-1][secondlargest] = temp

print(arr2)

[[89 81 88 92 32 54]
 [ 8 95 72 40 74 72]
 [61 62 19 82 85 43]
 [74 40 60 54 66 38]
 [ 7 15 50 31 40  4]]


In [72]:
nparr = np.random.randint(1,100, (5,6))
print(nparr)

# get them
numrow, numcol = nparr.shape
largest = np.argsort(nparr)[numrow-1][-1]
secondlargest = np.argsort(nparr)[numrow-1][-2]

smallest = np.argsort(nparr)[0][0]
secondsmallest = np.argsort(nparr)[0][1]

# change them
temp = nparr[0][smallest]
nparr[0][smallest] = nparr[numrow-1][largest]
nparr[numrow-1][largest] = temp

temp = nparr[0][secondsmallest]
nparr[0][secondsmallest] = nparr[numrow-1][secondlargest]
nparr[numrow-1][secondlargest] = temp

print(nparr)

[[28 90 33 84 62 42]
 [29 91 64 79  7 76]
 [37 52 99 55 21 18]
 [45 12 43 84 52 77]
 [12 97 23 46 54 58]]
[[97 90 58 84 62 42]
 [29 91 64 79  7 76]
 [37 52 99 55 21 18]
 [45 12 43 84 52 77]
 [12 28 23 46 54 33]]


In [81]:
target = '#a?a b#  '
pattern = r'\s*(.)\s*(.)\s*(.)\s*(\2)\s*(\1)\s*'
result = re.match(pattern, target)
print(result)

None


In [102]:
target = "431e20"
target = "1.23E15"
pattern = r'(^\d{1,}[eE][1-9]\d*$)|(^\d{1,}\.\d{1,}[eE][1-9]\d*$)'
pattern = r'(^\d{1,}[eE][1-9]\d*$)|(^\d{1,}\.\d{1,}[eE][1-9]\d*$)'
print(re.match(pattern, target))

<re.Match object; span=(0, 7), match='1.23E15'>


In [113]:
target = "c2f_con19Tsdfv_"
target = "cf#"
pattern = r'^[a-zA-Z]\w*$'
print(re.match(pattern, target))

None


In [135]:
# 1.2
target = '0-2.3'
target = ' 01*278  '
# pattern needs to work with ints as operands
# first points
# second points
# middle points
pattern1 = r'^\s*(\d{1,})\s*([\+\-\*\/])\s*(\d{1,})\s*$'
pattern2 = r'^\s*(.?\d{1,})\s*([\+\-\*\/])\s*(\d{1,})\s*$'
pattern3 = r'^\s*(\d{1,}.?\d*)\s*([\+\-\*\/])\s*(\d{1,}.?\d*)\s*$'
pattern4 = r'^\s*(.?\d{1,})\s*([\+\-\*\/])\s*(.?\d{1,})\s*$'
pattern5 = r'^\s*(.?\d{1,})\s*([\+\-\*\/])\s*(\d{1,}.?\d*)\s*$'
pattern = pattern1 + "|" + pattern2 + "|" + pattern3 + "|" + pattern4 + "|" + pattern5

targets = [' 01*278  ',
' 1.23 f+16',
'.2/5.',
'0-23.']
for target in targets:
    print(re.findall(pattern, target))

[('01', '*', '278', '', '', '', '', '', '', '', '', '', '', '', '')]
[]
[('', '', '', '', '', '', '', '', '', '', '', '', '.2', '/', '5.')]
[('', '', '', '', '', '', '0', '-', '23.', '', '', '', '', '', '')]


In [158]:
a = np.random.randint(0,100, (6,4))

In [159]:
print(a)

[[80  7  8 70]
 [11 49 20 62]
 [54 50 12 25]
 [98 91 27 68]
 [35 68 97  3]
 [36 68 31 91]]


In [160]:
arr = a.mean(axis=0)
means = arr.mean()
a = a > means
print(a)

myarr = a.all(axis=0)
print(myarr)

[[ True False False  True]
 [False  True False  True]
 [ True  True False False]
 [ True  True False  True]
 [False  True  True False]
 [False  True False  True]]
[False False False False]


In [161]:
print(filter)

12.5
